apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: debian
spec:
  selector:
    matchLabels:
      app: debian
  replicas: 1
  template:
    metadata:
      labels:
        app: debian
    spec:
      containers:
      - name: debian
        image: tolaose/debian
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 3

---
apiVersion: v1
kind: Service
metadata:
  name: debian
  labels:
    app: debian
    name: debian
spec:
  selector:
    app: debian
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
